apiVersion: v1
kind: Pod
metadata:
  name: pending-pod
spec:
  containers:
  - name: pending-container
    image: busybox
    command: [ "sleep", "3600" ]
    resources:
      requests:
        memory: "1Ti" # Request an unreasonable amount of memory
  restartPolicy: Never
